name: Build and Lint

on:
  push:
    branches:
      - 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ''

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint